{% set name = "ipyflex" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4a2a85c32e2cedcc32d3c0bd2e4b0636fc16beea60aae4a1a4f6c24cb86a484

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging =0.10
  run:
    - ipywidgets >=7.6.0
    - python >=3.6

test:
  imports:
    - ipyflex

about:
  home: https://github.com/trungleduc/ipyflex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A WYSIWYG layout editor for Jupyter widgets
  doc_url: https://ipyflex.readthedocs.io
  dev_url: https://github.com/trungleduc/ipyflex

extra:
  recipe-maintainers:
    - trungleduc
