{% set name = "ipyflex" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdafb7f24f84b8175e0a91277b0fba997dda198fb445fb06b3ae812fc3e7a78b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - python >=3.8
    - ipywidgets >=8

test:
  imports:
    - ipyflex

about:
  home: https://github.com/trungleduc/ipyflex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A WYSIWYG layout editor for Jupyter widgets
  doc_url: https://ipyflex.readthedocs.io
  dev_url: https://github.com/trungleduc/ipyflex

extra:
  recipe-maintainers:
    - trungleduc
